apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: flask-app
        image: <ECR_REPOSITORY_URI>:latest
        ports:
        - containerPort: 5000
        env:
        - name: RDS_ENDPOINT
          value: "<RDS_ENDPOINT>"
        - name: RDS_USERNAME
          value: "admin"
        - name: RDS_PASSWORD
          value: "<PASSWORD>"
        - name: RDS_DATABASE
          value: "mydb"
